from os.path import join

DATA_FOLDER           = "data"
OUTPUT_FOLDER         = "outputs"

NAME_FILE_AAAA        = 'aaaa.dat'
NAME_FILE_ZZZZ        = 'ZZZZ.dat'
NAME_FILE_MAIN        = 'main.dol'
NAME_FILE_RESULTS     = 'results.json'
NAME_FILE_FILENAMES   = 'FileNames.json'

US_FOLDER             = 'US'
US_DATA_FOLDER        = join(DATA_FOLDER,        US_FOLDER)
US_OUTPUT_FOLDER      = join(OUTPUT_FOLDER,      US_FOLDER)
US_AAAA_FILE          = join(US_DATA_FOLDER,     NAME_FILE_AAAA)
US_ZZZZ_FILE          = join(US_DATA_FOLDER,     NAME_FILE_ZZZZ)
US_MAIN_FILE          = join(US_DATA_FOLDER,     NAME_FILE_MAIN)
US_RESULTS_FILE       = join(US_OUTPUT_FOLDER,   NAME_FILE_RESULTS) 
US_CUSTOM_FILENAMES   = join(US_DATA_FOLDER,     NAME_FILE_FILENAMES) 

JP_FOLDER             = 'JP'
JP_DATA_FOLDER        = join(DATA_FOLDER,        JP_FOLDER)
JP_OUTPUT_FOLDER      = join(OUTPUT_FOLDER,      JP_FOLDER)
JP_AAAA_FILE          = join(JP_DATA_FOLDER,     NAME_FILE_AAAA)
JP_ZZZZ_FILE          = join(JP_DATA_FOLDER,     NAME_FILE_ZZZZ)
JP_MAIN_FILE          = join(JP_DATA_FOLDER,     NAME_FILE_MAIN)
JP_RESULTS_FILE       = join(JP_OUTPUT_FOLDER,   NAME_FILE_RESULTS) 
JP_CUSTOM_FILENAMES   = join(JP_DATA_FOLDER,     NAME_FILE_FILENAMES) 

EU_FOLDER           = 'EU'
EU_DATA_FOLDER        = join(DATA_FOLDER,        EU_FOLDER)
EU_OUTPUT_FOLDER      = join(OUTPUT_FOLDER,      EU_FOLDER)
EU_AAAA_FILE          = join(EU_DATA_FOLDER,     NAME_FILE_AAAA)
EU_ZZZZ_FILE          = join(EU_DATA_FOLDER,     NAME_FILE_ZZZZ)
EU_MAIN_FILE          = join(EU_DATA_FOLDER,     NAME_FILE_MAIN)
EU_RESULTS_FILE       = join(EU_OUTPUT_FOLDER,   NAME_FILE_RESULTS) 
EU_CUSTOM_FILENAMES   = join(EU_DATA_FOLDER,     NAME_FILE_FILENAMES) 

BETA_FOLDER           = 'Beta'
BETA_DATA_FOLDER      = join(DATA_FOLDER,        BETA_FOLDER)
BETA_OUTPUT_FOLDER    = join(OUTPUT_FOLDER,      BETA_FOLDER)
BETA_AAAA_FILE        = join(BETA_DATA_FOLDER,   NAME_FILE_AAAA)
BETA_ZZZZ_FILE        = join(BETA_DATA_FOLDER,   NAME_FILE_ZZZZ)
BETA_MAIN_FILE        = join(BETA_DATA_FOLDER,   NAME_FILE_MAIN)
BETA_RESULTS_FILE     = join(BETA_OUTPUT_FOLDER, NAME_FILE_RESULTS) 
BETA_CUSTOM_FILENAMES = join(BETA_DATA_FOLDER,   NAME_FILE_FILENAMES) 

